version: "3.9"

services:
  app:
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ./apps/admin/Dockerfile
    image: ${NEXUS_URL}/admin-${ENV}:${TAG}
    container_name: admin
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
